//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using HeroesDomainModel;
    
    public partial class HeroesDBEntities : DbContext
    {
        public HeroesDBEntities()
            : base("name=HeroesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Ability { get; set; }
        public virtual DbSet<Ability_Effect> Ability_Effect { get; set; }
        public virtual DbSet<Build> Build { get; set; }
        public virtual DbSet<Effect> Effect { get; set; }
        public virtual DbSet<Hero> Hero { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Talent> Talent { get; set; }
        public virtual DbSet<Universum> Universum { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Replay> Replay { get; set; }
        public virtual DbSet<Average_Stats> Average_Stats { get; set; }
        public virtual DbSet<Stats> Stats { get; set; }
    }
}
