//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesManagerDeluxe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeroesManagerDeluxe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Details.
        /// </summary>
        internal static string Command_BuildDetail {
            get {
                return ResourceManager.GetString("Command_BuildDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Build.
        /// </summary>
        internal static string Command_CreateBuild {
            get {
                return ResourceManager.GetString("Command_CreateBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero Details.
        /// </summary>
        internal static string Command_HeroDetail {
            get {
                return ResourceManager.GetString("Command_HeroDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Build.
        /// </summary>
        internal static string Command_SaveBuild {
            get {
                return ResourceManager.GetString("Command_SaveBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Command.
        /// </summary>
        internal static string Command_Search {
            get {
                return ResourceManager.GetString("Command_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Command_UpdateTalents {
            get {
                return ResourceManager.GetString("Command_UpdateTalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string Name_BuildViewModel {
            get {
                return ResourceManager.GetString("Name_BuildViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        internal static string Name_HeroesListViewModel {
            get {
                return ResourceManager.GetString("Name_HeroesListViewModel", resourceCulture);
            }
        }
    }
}
