//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ability_Effect
    {
        public int ability_id { get; set; }
        public int effect_id { get; set; }
        public int value { get; set; }
        public int time { get; set; }
        public Nullable<int> talent_id { get; set; }
        public int id { get; set; }
        public float talented_value { get; set; }
        public float talented_time { get; set; }
    
        public virtual Ability Ability { get; set; }
        public virtual Effect Effect { get; set; }
        public virtual Talent Talent { get; set; }
    }
}
