//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Average_Stats
    {
        public Average_Stats()
        {
            this.Stats = new HashSet<Stats>();
        }
    
        public int id { get; set; }
        public float average_hero_damage { get; set; }
        public float average_siege_damage { get; set; }
        public float average_role { get; set; }
        public float average_xp_contribution { get; set; }
        public int number_of_games { get; set; }
        public int hero_id { get; set; }
    
        public virtual ICollection<Stats> Stats { get; set; }
    }
}
