//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public Hero()
        {
            this.Ability = new HashSet<Ability>();
            this.Build = new HashSet<Build>();
            this.Comment = new HashSet<Comment>();
            this.Stats = new HashSet<Stats>();
            this.Talent = new HashSet<Talent>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public int universum_id { get; set; }
        public int role_id { get; set; }
        public int base_hp { get; set; }
        public float hp_coefficient { get; set; }
        public int base_energy { get; set; }
        public float energy_coefficient { get; set; }
        public int base_attack_dmg { get; set; }
        public int attack_dmg_coefficient { get; set; }
        public float attack_speed { get; set; }
        public bool owned { get; set; }
    
        public virtual ICollection<Ability> Ability { get; set; }
        public virtual ICollection<Build> Build { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Role Role { get; set; }
        public virtual Universum Universum { get; set; }
        public virtual ICollection<Stats> Stats { get; set; }
        public virtual ICollection<Talent> Talent { get; set; }
    }
}
