//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replay
    {
        public int id { get; set; }
        public int replay1 { get; set; }
        public int stats_id { get; set; }
    
        public virtual Stats Stats { get; set; }
    }
}
