//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int id { get; set; }
        public int average_stats_id { get; set; }
        public int user_id { get; set; }
        public int hero_id { get; set; }
        public int hero_damage { get; set; }
        public int siege_damage { get; set; }
        public int role { get; set; }
        public int xp_contribution { get; set; }
        public float player_average_hero_damage { get; set; }
        public float player_average_siege_damage { get; set; }
        public float player_average_role { get; set; }
        public float player_average_xp_contribution { get; set; }
        public int number_of_games { get; set; }
    
        public virtual Average_Stats Average_Stats { get; set; }
        public virtual Hero Hero { get; set; }
        public virtual User User { get; set; }
    }
}
