//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talent_Build
    {
        public int build_id { get; set; }
        public int Talent_id { get; set; }
        public bool is_selected { get; set; }
    
        public virtual Build Build { get; set; }
        public virtual Talent Talent { get; set; }
    }
}
