//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talent
    {
        public Talent()
        {
            this.Talent_Build = new HashSet<Talent_Build>();
            this.Ability_Effect = new HashSet<Ability_Effect>();
            this.Build = new HashSet<Build>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int lvl { get; set; }
        public int ability_id { get; set; }
        public int build_id { get; set; }
        public int hero_id { get; set; }
    
        public virtual Ability Ability { get; set; }
        public virtual ICollection<Talent_Build> Talent_Build { get; set; }
        public virtual ICollection<Ability_Effect> Ability_Effect { get; set; }
        public virtual Hero Hero { get; set; }
        public virtual ICollection<Build> Build { get; set; }
    }
}
