//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroesDomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Stats = new HashSet<Stats>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public bool admin_permission { get; set; }
    
        public virtual ICollection<Stats> Stats { get; set; }
    }
}
